### ISSUE TITLE
Create Video Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#419] opened 2019-01-04 20:32 UTC
This story is to create the [Video](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Video) content type.

**User Story:**
- As a content author I would like to create a Video content type on cancer.gov so that I may embed a YouTube video on a cancer.gov page.. 

**Acceptance Criteria:**
- I am required to enter the following Common Fields:

- I have the option to enter the following Common Media Fields:
  * [Caption](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#caption)
  * [Original Source](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#original-source)

**Comment by VictoriaSunNIH** [comment] 2019-01-30 17:54
Closing as a duplicate of #220

**Closed by VictoriaSunNIH** 2019-01-30 17:54 UTC
