### ISSUE TITLE
Event content Type: Date & Time Issues

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1971] opened 2019-06-12 15:40 UTC
Description : When the start date is 06/12/2019, it allows user to select end date as 06/11/2019 and at the front end displays the time of Start date and End date under the Start day label

Screen-shot for Input Date and times

![image](https://user-images.githubusercontent.com/28455973/59365466-9758a500-8d06-11e9-850a-f3f4d75c4415.png)

Screen-shot for the Date and Time as it is displayed at the front end
![image](https://user-images.githubusercontent.com/28455973/59365580-c40cbc80-8d06-11e9-8d97-4265288f1220.png)

**Comment by andyvanavery31** [comment] 2024-06-26 19:42
Duplicate of #2922 this will be closed.

**Closed by andyvanavery31** 2024-06-26 19:42 UTC
Labels: bug
