### ISSUE TITLE
Home and Landing: Build hero banner

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#47] opened 2018-11-19 21:39 UTC
[Hero Banner](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-Page#layout-builder-regions) consists of:
* HTML block that displays provided text on top of the homepage hero banner image at desktop and tablet breakpoints
* Images (desktop and tablet) for the banner

Hero Banner does not display on Mobile

**Comment by amydugan** [comment] 2019-01-25 19:36
Closing out as this was associated with the layout builder Home/Landing ticket. It is a duplicate of https://app.zenhub.com/workspaces/cgov-digital-platform-5c0fc73f4b5806bc2bfc78bd/issues/nciocpl/cgov-digital-platform/310.

**Closed by amydugan** 2019-01-25 19:36 UTC
