### ISSUE TITLE
Mobile Display Issues for Guide Card Row on Home/Landing Pages (lower priority)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1615] opened 2019-05-02 21:54 UTC
When I shrink my browser size down to mobile, the alternating blue accordions used in the guide card row on home/landing pages do not fully display across the screen. See screenshot comparing the live site to the dev ODE:

![Screen_Shot_2019-05-02_at_5_38_10_PM](https://user-images.githubusercontent.com/29731392/57109337-31d6c900-6d03-11e9-90cf-98b539e322ad.png)

**Comment by BrendanBeltzNIH** [comment] 2019-05-02 22:38
This is a duplicate of #1531

**Closed by BrendanBeltzNIH** 2019-05-02 22:38 UTC
Labels: bug
