### ISSUE TITLE
Anonymous users viewing an unpublished page should get a 404

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1741] opened 2019-05-16 20:06 UTC
When an anonymous user views a page in the following states, they should not recieve an access denied message, but instead get sent to our 404 page(s):
- Unpublished (draft)
- Review (draft)
- Archived 

They should see a "page not found" and the server should return a 404.

**Comment by blairlearn** [comment] 2023-10-05 16:26
Duplicate of #1708 .

**Closed by blairlearn** 2023-10-05 16:26 UTC
Labels: Medium priority, Unpublished Link Thingy
