### ISSUE TITLE
Add validation to yaml_content imports

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#1111] opened 2019-03-20 18:48 UTC
Encountered on #1054, yaml_content allows invalid content to be imported because it doesn't validate entities' content before saving.

We should add a
```
$violations = $entity->validate();
// process violations here
```
to the ENTITY_PRE_SAVE event in cgov_yaml_content module (or patch the yaml_content module to do it).

Background: https://www.drupal.org/project/drupal/issues/2085071
> "An invalid entity is not something unexpected, so I'm not convinced about using exceptions for violations. It is something you can and should check in advance." -bedir same issue

> "Yes, it sucks a lot but we do have to keep supporting in-valid data. "  - fago

**Comment by VictoriaSunNIH** [comment] 2021-03-29 15:25
Closing this as a duplicate of #857

**Closed by VictoriaSunNIH** 2021-03-29 15:25 UTC
Labels: Technical Item, bug
