### ISSUE TITLE
Resolve CDR Publish Preview Percussion dependencies

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1074] opened 2019-03-15 16:09 UTC
This requires changes in both the CDR and GateKeeper.

## Drug and Cancer Info Summaries
Render in the CDR with the same XSL Transforms as are used for sending the content to Drupal. The Drupal system only needs to be responsible for supplying a basic "C-clamp" with the necessary CSS and JavaScript. The CDR already knows the correct versions of any required media files and can include the correct references in the rendering without requiring any post-processing.

## Other document types
This needs more details, but it would be good to do the rendering and then embed the result in the same "C-clamp" as mentioned above. Possibly change from returning a full-blown page to just returning the rendered result, ready to be injected into the C-clamp by the calling system.

**Comment by VictoriaSunNIH** [comment] 2019-03-18 17:45
Duplicate of #1070

**Closed by VictoriaSunNIH** 2019-03-18 17:45 UTC
Labels: Technical Item
