### ISSUE TITLE
Load site sections using the migrate module in addition to our YAML content

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#978] opened 2019-03-06 21:45 UTC
## Description 

Load the *real* CancerGov site section list when loading YAML content.

**Comment by amydugan** [comment] 2019-04-11 18:53
This is a dupe of #1340

**Closed by amydugan** 2019-04-11 18:53 UTC
Labels: In Scope (June 2019), Technical Item, on-hold

**Comment by blairlearn** [comment] 2019-04-16 18:01
Technically, #1340 was the dupe of this one. :-p
