### ISSUE TITLE
All factbook pages shows console error on Prod 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3336] opened 2022-03-30 14:16 UTC
### Issue description

All factbook pages shows console error on Prod 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to  https://www.cancer.gov/about-nci/budget/fact-book/data/extramural
2. Open the console and refresh the page.
3. See the error "offline-exporting.src.js:230 Uncaught TypeError: Cannot read properties of undefined (reading 'ajax')"

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- 
![image](https://user-images.githubusercontent.com/28455973/160855917-fdeadff0-7bc1-485c-ac2d-b977b26fe1fe.png)

### Related Tickets
* Issue #9999
* Issue #9999

cc: @blairlearn , @VictoriaSunNIH

**Comment by laurelthrash** [comment] 2022-11-01 19:50
Unable to reproduce in Production as of 11/1. Closing this ticket. Cc: @sarinapadilla @andyvanavery @santwuma

**Closed by laurelthrash** 2022-11-01 19:50 UTC
Labels: bug
