### ISSUE TITLE
BUG: Intro Text styling on Article/Blog pages

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#1031] opened 2019-03-12 16:13 UTC
Intro Text on Article/Blog pages should be marked with ".blog-intro-text p" as it appears on cgov site. 
attaching screenshots for Stage and Prod.

<img width="1231" alt="Screen Shot 2019-03-12 at 10 35 53 AM" src="https://user-images.githubusercontent.com/46539699/54214275-5315f880-44bc-11e9-91ce-9ed524cf9635.png">
<img width="1287" alt="Screen Shot 2019-03-12 at 11 30 58 AM" src="https://user-images.githubusercontent.com/46539699/54214276-5315f880-44bc-11e9-951e-312c24cd5d5d.png">

**Comment by alifr** [comment] 2019-03-19 17:04
essentially a duplicate of #843

**Comment by VictoriaSunNIH** [comment] 2019-04-03 18:54
CLosing this as a dupe of #843

**Closed by VictoriaSunNIH** 2019-04-03 18:54 UTC
Labels: In Scope (June 2019), Needs IA Review, bug, duplicate
