### ISSUE TITLE
Placeholder: Hook up CDR to CMS

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#825] opened 2019-02-19 16:36 UTC

**Comment by blairlearn** [comment] 2019-02-21 16:19
Discussion item: GateKeeper impact.

During an earlier conversation, @bkline and I had discussed that GateKeeper would not change. There's a risk to this of interfering with unknown dependencies on the CDR side. One approach is to continue sending data to GateKeeper, however this requires modifying GateKeeper to no longer connect to Percussion.

**Comment by blairlearn** [comment] 2019-02-21 21:05
I've put together a list of changes for GateKeeper at: https://github.com/NCIOCPL/wcms-gatekeeper/wiki/Remove-Percussion-Dependency.

My assumption is that GateKeeper will accept, but not actually process:
* Cancer Information Summaries
* Drug Information Summaries
* Image media files
* Audio media files

In all four cases, GateKeeper will simply record and report that the documents were processed successfully.

This includes **disabling publishing preview** for Cancer and Drug Summaries

**Comment by bkline** [comment] 2019-02-21 21:09
From my last conversation with @bryanpizzillo, we are currently planning to serve the media files from the old system, and won't switch over to the Akamai storage until after launch. Of course, the game plan may have changed since that discussion, but I haven't gotten that memo. Also of course, I can always have misunderstood what he was trying to tell me. 😃  But if I did understand correctly, and things haven't changed (yet), GateKeeper will still need to process the media files.

**Comment by bkline** [comment] 2019-02-25 18:04
# Considerations

1.  GateKeeper

    We will eliminate GateKeeper eventually, but this will not happen until
    some time after the initial launch of the new Drupal CMS.

2.  Initial Load

    At the initial launch of the new CMS a one-time job will be run to load
    the PDQ summaries (both cancer and drug info) into Drupal. From then on,
    the CDR publishing job will update the Drupal CMS to add, update, and
    remove summaries as appropriate.

3.  Impact Analysis

    We will not have the tools in place for tracking links between content
    nodes in time for the initial launch. This means that it will not be
    possible for the PDQ APIs to determine whether it is safe to delete a
    PDQ Summary (because it can't tell what other content links to it).
    The CDR is responsible for preventing broken links between PDQ content
    items, but has no record of links from other Drupal content items to
    the PDQ summaries. We will therefore either need to block summary deletions
    at the outset if feasible (not likely) or rely on manual checks to determine
    whether deletion of a PDQ summary is safe.


# Tasks

1.  Add tables needed to track documents in Drupal CMS

2.  Implement /pdq/api/list

3.  Implement new Python class in cdrapi.publishing module

    We need a class to communicate with the PDQ APIs in the Drupal CMS,
    called something like DrupalClient, providing functionality comparable
    to that provided by the cdr2gk Python module.

4.  Extend the cdrpub module

    The code which handles CDR publishing "push" jobs will push the PDQ
    summaries to both the GateKeeper and to the Drupal CMS. The job will
    be marked as completed successfully only when both of these actions
    has finished and been confirmed.

**Comment by bkline** [comment] 2019-03-18 13:47
I believe all of the tasks for this ticket (with the exception of adding special tables to track exported documents separately for each Drupal target, which was abandoned on the advice of Blair) are done.

**Closed by bkline** 2019-03-18 13:47 UTC
Labels: EPIC
