### ISSUE TITLE
Change paragraph type: body_section field field_body_section_heading from text plain to HTML streamlined

### ISSUE THREAD

**Issue by zhuomingao** [NCIOCPL/cgov-digital-platform#1043] opened 2019-03-13 14:08 UTC
field_body_section_heading needs to be changed to allow simple HTML since there is currently content in percussion that has markup like <I> in heading, e.g. fact sheet questions

**Comment by VictoriaSunNIH** [comment] 2019-03-13 15:23
Closing as a duplicate of #621

**Closed by VictoriaSunNIH** 2019-03-13 15:23 UTC
Labels: Technical Item
