### ISSUE TITLE
Streamlined HTML content is not properly glossified

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2212] opened 2019-07-17 17:21 UTC
It looks like the relevant tags are being stripped out.
The page is https://www.cancer.gov/about-cancer/diagnosis-staging/diagnosis where this occurred.

Into HTML
![image](https://user-images.githubusercontent.com/11215649/61396370-9252bc80-a895-11e9-9479-34e2536dcced.png)

Working definitions in body on the same page:
![image](https://user-images.githubusercontent.com/11215649/61396422-b6160280-a895-11e9-9c82-0581489dfa08.png)

**Comment by VictoriaSunNIH** [comment] 2019-07-25 14:11
Closing this as a dupe of #2246

**Closed** 2019-07-25 15:25 UTC
Labels: High priority, bug
