### ISSUE TITLE
Build out Drug Dictionary API and Loader

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#215] opened 2018-12-14 15:56 UTC
This story is to build out the API and Loader for Drug Dictionary and Autosuggest.

**Comment by bkline** [comment] 2019-01-31 02:17
I guess I need a little clarification on the difference between this ticket and #569.

**Comment by amydugan** [comment] 2019-02-04 20:14
closing as a duplicate of https://github.com/NCIOCPL/cgov-digital-platform/issues/569

**Closed by amydugan** 2019-02-04 20:14 UTC
