### ISSUE TITLE
Console error appears on loading PDQ summaries

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2992] opened 2020-12-15 20:00 UTC
### Issue description

Getting console error on loading PDQ summaries. Test url: https://www.cancer.gov/types/childhood-cancers/late-effects-pdq

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/102266279-37881f00-3ee6-11eb-9820-10be8da21e75.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment] 2020-12-15 20:03
Duplicate of #2973

**Closed by blairlearn** 2020-12-15 20:03 UTC
Labels: bug
