### ISSUE TITLE
Update platform to use CKEditor4 LTS Contributed module

### ISSUE THREAD

**Issue by navsunka** [NCIOCPL/cgov-digital-platform#4123] opened 2023-10-19 18:58 UTC
Update the platform to use https://www.drupal.org/project/ckeditor_lts instead of the core ckeditor. This editor requires a license key so we will handle that via settings.

**Comment by bryanpizzillo** [comment] 2023-11-09 18:03
Closing this as it is a dupe of 4123 now.

**Closed by bryanpizzillo** 2023-11-09 18:03 UTC
