### ISSUE TITLE
Mobile (Android)-  For microsites, the link back is not center aligned at the top of the mobile menus on androids 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2305] opened 2019-08-06 15:48 UTC
For microsites, the link back is not center aligned at the top of the mobile menus on androids 
Steps to reproduce:
1. Go to https://www.cancer.gov/rare-brain-spine-tumor/
2. Click the hamburger menu and see that the  link back is not center aligned 

![image](https://user-images.githubusercontent.com/28455973/62554599-5fba3500-b83f-11e9-81d2-d412b1e50149.png)

**Comment by amydugan** [comment] 2019-08-12 17:31
@arcepaul - Lynn and Kevin gave the go-ahead to include the partial fix in the 1.1.5 Release 8/15/19. 

Kevin wanted to know we have a general sense of "how old" the Android devices are, generally, that are having issues? And if it's all out-of-date Chrome and device-specific browsers that are having the issues? (Going live with the current fix isn't contingent upon the answer.)

**Comment by amydugan** [comment] 2019-08-13 14:13
@markecramer @arcepaul - Is this issue something that will need to be fixed in DTM?

**Comment by markecramer** [comment] 2019-08-13 17:59
@amydugan , it looks like the issue isn't with the linkback itself. The width of the page, when the menu is open, is wider than the screen. This can be viewed by going to the bottom of the menu and observing a horizontal scrollbar exists.

Not sure if something could be done on the linkback to overcome this issue, like giving it a maximum width of the viewport size. I'll look into that.

**Comment by sarinapadilla** [comment] 2024-04-26 18:03
Closing since this has been updated with redesign.

**Closed by sarinapadilla** 2024-04-26 18:03 UTC
Labels: bug
