### ISSUE TITLE
Allow editor role to embed block content and infographics

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1479] opened 2019-04-16 15:51 UTC
When logged into dev as an editor, I cannot access the Content Browsers for:
- Insert Block Content
- Insert Infographic

Please update the config to allow editors to add this content.

**Comment by BrendanBeltzNIH** [comment] 2019-04-17 12:45
This is a part duplicate of #1442 . Suggest close #1442 in favor of this.

**Comment by VictoriaSunNIH** [comment] 2019-04-17 12:52
Done! #1442 has been closed as a dupe.

**Closed** 2019-04-19 18:35 UTC
Labels: In Scope (June 2019), Medium priority, bug
