### ISSUE TITLE
Unable to close site section once its open on mobile

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1766] opened 2019-05-20 16:03 UTC
Once a user clicks to open the section nav menu (the "tongue") when viewing on mobile or tablet, the menu disappears, and users are unable to close the section nav.

![image](https://user-images.githubusercontent.com/31222859/58035667-4551a480-7af7-11e9-9e95-a9bd3b3fb59c.png)

**Comment by VictoriaSunNIH** [comment] 2019-05-20 18:08
Closing as a duplicate of #1757

**Comment by BrendanBeltzNIH** [comment] 2019-05-21 16:29
So, once again. This is something that was ported correctly from prod at the time, but a release was done on FEQ 3 months ago fixing it without telling us to update to match. We could have done with some clearer lines of communication on tickets obviously.

**Comment by BrendanBeltzNIH** [comment] 2019-05-21 21:48
Duplicate of #1536

**Closed** 2019-05-23 17:31 UTC
Labels: High priority, bug
