### ISSUE TITLE
Deleting Site Sections does not remove from section navigation

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2903] opened 2020-08-28 14:32 UTC
### Issue description
Deleting a site section does not remove the items from the section and left navigation. 

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Delete a site section
2. Go to the page
3. See the site section appear

### What's the expected result?
- Deleting a site section should remove the site section and applicable children from the left navigation

### What's the actual result?
- Site sections persist until parent page is republished. 

### Additional details / screenshot
- found during removal of Terminology pages from Resources for Researchers: https://www.cancer.gov/research/resources/about (Used to be final menu item under cryo EM)
- Order of actions taken: archived pages, deleted pages, set up redirects, removed site sections by deleting parent
- Before site sections were removed, clicking on them redirected to the new pages

**Comment by andyvanavery31** [comment] 2023-12-07 16:40
Closing due to unable to reproduce with the new side nav.

**Closed by andyvanavery31** 2023-12-07 16:40 UTC
Labels: bug
