### ISSUE TITLE
Combo Box Analytics - no Results

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4313] opened 2024-04-17 17:31 UTC
Reported by Joe during testing on the ODE:

One thing on the analytics that we need to have a look at is the "No result found" event. 

I think we had discussed trying to look at ways to limit that from firing off endlessly or to not keep firing off if someone just keeps typing away. 

Example: if the user type "breat" the event would fire, but kept typing "breath", "breathm", "breathmi", "breathmin", "breathmint", the event would fire off 5 additional times. If the user begins deleting characters, it would fire again for each character deleted.

**Comment by bryanpizzillo** [comment] 2024-04-17 17:45
Closing this as a dupe of #4303

**Closed by bryanpizzillo** 2024-04-17 17:45 UTC
