### ISSUE TITLE
Investigate SAML Login Config -- Unable to log out of www-cms.cancer.gov

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2465] opened 2019-10-02 18:52 UTC
There seems to be an issue with the SAML setup on www-cms.cancer.gov. 

I am unable to log out of the application (if using either NIH password or PIV card). Once I select 'logout' I seem to be pushed back through the SAML login automatically and I am returned back to the logged in view of the system.

**Comment by jfrank-nih** [comment] 2022-03-03 01:24
I believe this and #2061 are duplicates. Also, the issue is still occurring because I noticed it after the Okta troubles tonight when I was trying to log out of the site to see what IDP I would get to log back in.

**Comment by jfrank-nih** [comment] 2023-02-09 08:58
Closing as duplicate.

**Closed** 2023-02-09 09:32 UTC
Labels: Technical Item
