### ISSUE TITLE
Enabler: Turn on NCIDS Back to Top

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3348] opened 2022-04-05 18:42 UTC
# Turn on NCIDS Back to Top

This ticket is for pulling in the component from the DS, and implementing the analytics code to fire off when clicked.

DS component ticket: https://github.com/NCIOCPL/ncids/issues/374

> **ESTIMATE** 3

This should just be making sure the sass is included in common.css and turning on the JS in common.js.

### Acceptance Criteria for Analytics
``` gherkin
Scenario:
Given a user is on any page of cancer.gov
When the user clicks on the back to top button
Then there should be an NCIDataLayer Other event 
  And the event has the name “ReturnToTop:LinkClick”
  And the event has the the linkname “ReturnToTop:LinkClick”
  And this event should have the following data:
    | key      | value                                                                                           |
    | linkText | ReturnToTop                                                                                     |
```

**Comment by bennettcc** [comment] 2022-09-07 15:40
Closing this ticket - it is a duplicate of https://github.com/NCIOCPL/cgov-digital-platform/issues/3509

**Closed** 2022-09-07 15:40 UTC
Labels: Drupal - Redesign
