### ISSUE TITLE
Implement megamenu javascript

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3371] opened 2022-04-29 20:29 UTC
This note was here, but does not sound like it should be because it all works the same way... "make sure that we include specific examples like Key Initiatives under Research".

This story is to create a CgdpMegaMenuAdapter for use in initializing the NCIExtendedHeaderWithMegaMenu component. This will use the API that is being created in #3265.  Below is a rough sequence diagram of how this will work.

NOTE: If a primary navigation item does NOT have megamenu content, then clicking on that item should go directly to that section and not open up an empty mega menu. This applies to Spanish Grants and Training specifically.

```mermaid
sequenceDiagram
    actor Editor
    actor Visitor
    Editor->>/taxonomy/term/32/edit: Enters YAML Content for Mega Menu in Drupal
    Drupal->>/taxonomy/term/32/edit: Validates YAML
    Drupal->>/taxonomy/term/32/edit: Stores YAML

    Visitor->>Web Page: load
    Web Page->>+NCIExtendedHeaderWithMegaMenu: create()
    Visitor->>Web Page: click About Cancer (id: 32)
    Web Page->>NCIExtendedHeaderWithMegaMenu: handle click event
    NCIExtendedHeaderWithMegaMenu->>cgdpMegaMenuAdapter: getMegaMenuContent(id: 32)
    cgdpMegaMenuAdapter-)/taxonomy/term/32/mega-menu: Fetch Data
    /taxonomy/term/32/mega-menu-->>cgdpMegaMenuAdapter: json data
    cgdpMegaMenuAdapter-->>cgdpMegaMenuAdapter: Parse json and create HTML
    cgdpMegaMenuAdapter->>NCIExtendedHeaderWithMegaMenu: HtmlElement
    NCIExtendedHeaderWithMegaMenu-->>Web Page: Open Mega Menu Overlay
    NCIExtendedHeaderWithMegaMenu-->>Web Page: Display Html from adapter
  
```

**Comment by sarinapadilla** [comment] 2022-06-08 17:58
This is a duplicate of #3277, so closing this ticket.

**Closed by sarinapadilla** 2022-06-08 17:58 UTC
Labels: Drupal - Redesign
