### ISSUE TITLE
When users accounts are created their Admin language preference should be set to English.

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1230] opened 2019-03-26 19:26 UTC
When users accounts are created their Admin language preference should be set to English.

This should be done through creating a hook for creating user accounts to set the Admin Interface language to english

**Comment by amydugan** [comment] 2019-03-28 17:11
closing as dupe of #368

**Closed by amydugan** 2019-03-28 17:11 UTC
Labels: In Scope (May 2019)
