### ISSUE TITLE
Exit disclaimer injected incorrectly on external Feature Card

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1820] opened 2019-05-24 23:10 UTC
The page at https://www-dev-ac.cancer.gov/about-nci/organization/ccct contains two feature cards.

The second card is titled "External Card Title" and links to https://www.google.com/.

The exit disclaimer link on this card is being injected adjacent to the `<img>` element and  internally to the link to Google.

Snapshot of the DOM (edited for clarity):
```html
<div class="feature-card">
   <a href="https://www.google.com">
         <div class="image-hover">
           <img src="/sites/default/files/styles/cgov_featured/public/2019-05/find-clinical-trial-blue-feature-card-feat.jpg?itok=Ym7bfIzM" alt="Find a Clinical Trial" width="425" height="319">
           <a class="icon-exit-notification" title="Exit Disclaimer" href="undefined"><span class="hidden">Exit Disclaimer</span></a>
        </div>
        <h3>External Card Title</h3>
        <p>External Card Description</p>
      </a>
 </div>
```

**Comment by BrendanBeltzNIH** [comment] 2019-05-26 02:54
Why is this incorrect? You don't state expected behavior.

The exitDisclaimer has a piece of code that does this per a request.

![image](https://user-images.githubusercontent.com/34315527/58376766-f7e29680-7f3f-11e9-99e8-2d484fafa91f.png)

**Comment by BrendanBeltzNIH** [comment] 2019-05-31 13:47
I'm closing this because no reason for this being a bug is given and it matches prod behavior.

**Closed by BrendanBeltzNIH** 2019-05-31 13:47 UTC
Labels: bug
