### ISSUE TITLE
Infographics are initially created using /node paths instead of site sections.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1362] opened 2019-04-06 07:59 UTC
There's some funkiness in the infographics workflow with how or whether the desired path is shown.

1. Create a new infographic
1. Fill out the fields as usual
   * Set the site section to `/about`.
   * Set the pretty url to `pretty`.
1. Set the publishing state to `Published`.
1. The infographic's path will be `/node/{id}` (And it really is `/node`, not `/media`)
1. Edit the infographic.
1. Set workflow state to `Editing`.
1. Click "Save".
1. Edit the infographic again.
1. Set workflow state to `Published`.
1. Click "Save".
1. The infographic's path will only *now* be `/about/pretty`.

**Comment by VictoriaSunNIH** [comment] 2019-04-15 17:40
@lburack - please recheck this.

**Comment by BrendanBeltzNIH** [comment] 2019-04-16 02:26
@lburack - please recheck this.

**Comment by VictoriaSunNIH** [comment] 2019-04-16 13:18
@BrendanBeltzNIH - @lburack  and I both retested It looks like the above described scenario is still happening.  

The expected outcome is that when the content is saved as draft, it should have the pretty URL and its site section path in the URL.  Right now, even after saving and publishing twice, we see the pretty URL but not the site section path in the URL.

**Comment by adriancofie** [comment] 2019-04-18 16:04
@blairlearn @VictoriaSunNIH  The same issue in the #1496. It was caused by some code in a different PR overriding the logic.  I've fixed it in  #1496 so this just needs to be verified once thats approved.

**Comment by adriancofie** [comment] 2019-04-24 17:23
@VictoriaSunNIH @blairlearn  #1496 has already been merged in, so this just needs to be verified on  http://www-dev-ac.cancer.gov. and then can be closed.

**Comment by lburack** [comment] 2019-04-24 22:46
@adriancofie — what exactly got fixed? Is the URL of the infographic supposed to be correct no matter what the workflow is?

On http://www-dev-ac.cancer.gov, I created an infographic and pushed it directly to published; the infographic did not take on the site section and pretty URL given to it. I then followed @blairlearn's steps above, editing it and moving it back to published, and it then had the proper URL path. 

I then added another infographic, but pushed it to review first (instead of directly to published). Then I pushed it public and the URL path was correct. 

Just want to check what was fixed and ensure it's still fixed! CC @VictoriaSunNIH

**Closed** 2019-05-17 04:22 UTC
Labels: High priority, In Scope (June 2019), Technical Item, bug
