### ISSUE TITLE
Spanish pages use English social media images

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2697] opened 2020-03-16 19:11 UTC
### Issue description
When a Spanish page is shared to Facebook, the social media image used is the one from the English version of the page.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to a Spanish page which has a different lead image than its English counterpart.
2. View Page source.
3. Find the `<meta property="og:image"` tag

### What's the expected result?
- The URL should lead to the Spanish page's article image.

### What's the actual result?
- The URL leads to the English page's article image.

### Additional details
- As of this writing [the March 11 Spanish Cancer Currents blog entry](https://www.cancer.gov/espanol/noticias/temas-y-relatos-blog/2020/aprueba-fda-enfortumab-vedotina-cancer-vejiga) exhibits this problem.

**Comment by VictoriaSunNIH** [comment] 2020-10-08 17:47
Duplicate of #2884

**Closed by VictoriaSunNIH** 2020-10-08 17:47 UTC
Labels: bug
