### ISSUE TITLE
Users can add extra root site sections

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3394] opened 2022-05-25 15:50 UTC
### Issue description
If a user mistakenly marks more than one site section as the Main Nav Root, the system may at some indeterminate switch between them. If the "extra" section has no assigned megamenu, the entire megamenu will disappear.

To be clear, **This is a user error**. What's needed is a way to prevent the entire megamenu system from disappearing.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Create a new "Home" site section as a child of the "real" navigation root.
2. Put a checkmark in the box labeled "Set Main Nav Root".
3. Set other fields as normal.
5. Save the site section.

### What's the expected result?
- Ideally, the user would receive a warning message that a main navigation root has already been created. (An error is not desirable as there are situations, e.g. multiple languages, where two main roots are needed.)
- The megamenu should not disappear!

### What's the actual result?
- At some indeterminate interval (overnight?), the megamenu will be replaced with the contents of the "extra" root's megamenu hierarchy.

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/21063180/170304257-960bc002-2098-44d7-a744-8df5e40867ab.png)

### Related Tickets
* Issue #3062

**Comment by bryanpizzillo** [comment] 2022-06-01 00:59
I am going to close this. This is actually by design for those cases where there is a different main nav content for a subsection, aka, like the microsites of old. This is by design and we even have YAML to check this (and regression test scripts once our new nav stuff is in place).

This is probably a caching confusion. Mainnav blocks have a single cache tag which is mainnav, it does not use the cgov_site_section's id. Clearing this cache tag clears them out. **We do not want the site sections id as a cache tag cause any update will clear the cache of the entire site.** The only thing that can clear it out the pre-rendered block from drupal is the admin interface or a `drush cr` followed by any number of other cache clears. (`drush cr` does not trigger the purge module, but it does clear out the memcache for this cached item) 

The primary nav (and the side nav does basically the same thing) is drawn by:
1. Look at the requested URL
2. Find the closest site section to that URL (usually the site section with the same field_computed_path)
3. Starting with that site section, and traversing the parents, find the nearest site section that is marked as IsMainNavRoot.
4. The block then draws the children of that nav as the primary nav. 

What probably happened was some combination of:
1. a subpage was created/viewed without the parent section as being marked as primary nav root
    * The main nav got cached.
2. someone fiddled with that nav section.
    * This does not clear the cache for the main nav.
3. Some one cleared the cache or the main nav.
    * The main nav was cleared out of the cache.
4. The page was viewed and the new primary nav was rendered. Since none of the children existed, had landing pages, or were all marked as hide_in_primary_nav, the nav went empty.

**Closed by bryanpizzillo** 2022-06-01 00:59 UTC
Labels: bug

**Comment by blairlearn** [comment] 2022-06-07 12:42
If this is by design, then I won't reopen it.

The one thing I would note however is that after the cache is cleared, the "most root" nav will _only temporarily_ take over. In the case where the ccg content team encountered it, the site would switch to the other one overnight.
